1. What is a Python library? Why do we use Python libraries?

A Python library is a collection of pre-written code that provides functions, methods, and tools to perform specific tasks without having to write the code from scratch. Python libraries are used to enhance productivity, simplify complex tasks, and avoid reinventing the wheel.

2. What is the difference between Numpy array and List?

- **Numpy Array**: Homogeneous, faster, supports mathematical operations, and consumes less memory.  
- **List**: Heterogeneous, slower, does not support element-wise mathematical operations directly, and consumes more memory.

3. Find the shape, size and dimension of the following array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [2]:
import numpy as np

array = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12]])

shape = array.shape
size = array.size
dimension = array.ndim

shape, size, dimension

((3, 4), 12, 2)

4. Write python code to access the first row of the following array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [5]:
import numpy as np

array = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12]])

first_row = array[0]
first_row

array([1, 2, 3, 4])

5. How do you access the element at the third row and fourth column from the given numpy array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [6]:
import numpy as np

array = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12]])

element = array[2, 3]
element

12

6. Write code to extract all odd-indexed elements from the given numpy array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [7]:
import numpy as np

array = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12]])

odd_indexed_elements = array[1::2]
odd_indexed_elements

array([[5, 6, 7, 8]])

7. How can you generate a random 3x3 matrix with values between 0 and 1?

In [8]:
import numpy as np

random_matrix = np.random.rand(3, 3)
random_matrix


array([[0.00425211, 0.82542255, 0.72527954],
       [0.61108802, 0.5441104 , 0.14802704],
       [0.89777451, 0.22742699, 0.7311757 ]])

8. Describe the difference between np.random.rand and np.random.randn?



- `np.random.rand`: Generates random numbers from a uniform distribution between 0 and 1.  
- `np.random.randn`: Generates random numbers from a standard normal distribution with a mean of 0 and a standard deviation of 1.  

9. Write code to increase the dimension of the following array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [9]:
import numpy as np

array = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12]])

increased_dimension = np.expand_dims(array, axis=0)
increased_dimension


array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

10. How to transpose the following array in NumPy?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [ ]:
import numpy as np

array = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12]])

transposed_array = array.T
transposed_array


11. Consider the following matrix:

Matrix A: [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]

Matrix B: [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]

Matrix A

[[1, 2, 3, 4],
 [5, 6, 7, 8],
 [9, 10, 11, 12]]

 Matrix B

 [[1, 2, 3, 4],
 [5, 6, 7, 8],
 [9, 10, 11, 12]]


Perform the following operation using Python1

Index wise multiplicatio


In [ ]:
import numpy as np

A = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])

B = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])

result = A * B
result


 Matrix multiplicatio'

In [ ]:
import numpy as np

A = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])

B = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])

result = np.dot(A, B.T)
result


Add both the matricK

In [ ]:
import numpy as np

A = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])

B = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])

result = A + B
result


Subtract matrix B from 

In [ ]:
import numpy as np

A = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])

B = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])

result = A - B
result


 Divide Matrix B by A

In [ ]:
import numpy as np

A = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])

B = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])

result = B / A
result


12.  Which function in Numpy can be used to swap the byte order of an array?

The function `numpy.ndarray.byteswap()` can be used to swap the byte order of an array.

13.  What is the significance of the np.linalg.inv function?

The `np.linalg.inv` function is used to compute the **inverse** of a square matrix, provided the matrix is **invertible** (i.e., its determinant is not zero).

14. What does the np.reshape function do, and how is it used?



In [ ]:
import numpy as np

array = np.array([1, 2, 3, 4, 5, 6])
reshaped_array = np.reshape(array, (2, 3))


15. What is broadcasting in Numpy?

Broadcasting in NumPy refers to the ability to perform element-wise operations on arrays of different shapes. NumPy automatically expands the smaller array to match the shape of the larger array in a way that aligns the dimensions, without creating copies of the data, thus optimizing memory and computation.